### ISSUE TITLE
State?

### ISSUE THREAD

**Issue by q3cpma** [bvtthead/st-osc-8#4]
Hello, I know I could just test it, but do you think it's "finished", except for the two open issues?

By the way, using `execvp` with `config.h` variables to hold its file/argv arguments might be useful to users (to unify with plumbing, for example).

**Comment by bvtthead** [comment]
I would say it's more beta right now, I use it on my st build everyday and I haven't had any issues yet, but I also use tmux, which doesn't support osc 8 (https://github.com/tmux/tmux/issues/911). I forgot to push my latest commit which addresses #2.

There just needs to be more traffic to test it, but right now it's working well.
